name: publish-pydoctor-apidocs
on:
- push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pydoctor
      run: |
        python -m pip install -U pip pydoctor

    - name: Generate documentation
      run: |

        # Run pydoctor build
        pydoctor \
            --project-name=Saskatoon-Dev \
            --project-url=https://github.com/$GITHUB_REPOSITORY \
            --html-viewsource-base=https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA \
            --make-html \
            --html-output=./apidocs \
            --project-base-dir="$(pwd)" \
            --docformat=restructuredtext \
            --intersphinx=https://docs.python.org/3/objects.inv \
            ./saskatoon/app ./saskatoon/harvest ./saskatoon/member ./saskatoon/saskatoon

    - name: Publish apidocs to the gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate apidocs"