name: Run tests

on:
  push:
    branches: [ master, setup-tests]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install '.[test]'

    - name: Log system information
      run: |
        test -r /etc/os-release && sh -c '. /etc/os-release && echo "OS: $PRETTY_NAME"'
        python --version
        python -c "print('\nENVIRONMENT VARIABLES\n=====================\n')"
        python -c "import os; [print(f'{k}={v}') for k, v in os.environ.items()]"
    
    - name: Setup Django env
      run: |
        python3 saskatoon/tests/createtestsuperuser.py admin@example.com testing1234
      env:
          SASKATOON_TEST_DB_ENGINE: django.db.backends.sqlite3
          SASKATOON_TEST_DB_NAME: $GITHUB_WORKSPACE/test-database.db
          SASKATOON_TIME_ZONE: UTC
          SASKATOON_SECRET_KEY: 1234567890
          SASKATOON_DEBUG: no
    
    - name: Run tests
      run: |
        tox -e test
      env:
          SASKATOON_TEST_DB_ENGINE: django.db.backends.sqlite3
          SASKATOON_TEST_DB_NAME: $GITHUB_WORKSPACE/test-database.db
          SASKATOON_URL: http://localhost:8000
          SASKATOON_EMAIL: admin@example.com
          SASKATOON_PASSWORD: password1234
          SASKATOON_TIME_ZONE: UTC
          SASKATOON_SECRET_KEY: 1234567890
          SASKATOON_DEBUG: no

    # - name: Run mypy
    #   run: |
    #     tox -e mypy

    # - name: Run pyflakes
    #   run: |
    #     tox -e pyflakes
